name: webview_version
description: A flutter plugin to get webview version installed on the device.
version: 0.0.2
repository: https://github.com/madpocket/flutter_webview_version

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.madpocket.webview_version
        pluginClass: WebviewVersionPlugin
